SecureBankingSystem/SecureBank/urls.py
from django.conf.urls import url
from . import views
# from django.contrib.auth.views import login
# from django.contrib.auth.views import login_required


urlpatterns = [
    #url(r'^$', views.home),
    url(r'^login/', views.login_user, name='login'),
    url(r'^logout/', views.logout_user, name='logout'),
    # url(r'^staff/', views.home_internal_user, name='staff'),
    url(r'^fundtransfer/$', views.fundtransfer, name='fundtransfer'),
    url(r'^fundcredit/$', views.fundcredit, name='fundcredit'),
    url(r'^funddebit/$', views.funddebit, name='funddebit'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^user/$', views.home_external_user, name='user'),
    # url(r'^manager/$', views.home_internal_user, name='manager'),
    # url(r'^authorize_transaction/$', views.authorize_transaction, name='authorize_transaction'),
    url(r'^passbook/$', views.passbook, name='passbook'),
    url(r'^transaction_confirmation/(?P<transaction_id>[0-9]+)/$', views.transaction_confirmation,
        name='transaction_confirmation'),
    url(r'^$', views.index, name='index'),
]

SecureBankingSystem/SecureBankingSystem/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf.urls import url, include
from django.views.generic.base import RedirectView

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    # url(r'^admin/login$', RedirectView.as_view(pattern_name='login_user', permanent=True, query_string=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^SecureBank/', include('SecureBank.urls')),
    #url(r'^.*$', RedirectView.as_view(url='SecureBank/', permanent=True)),
]

SecureBankingSystem/SecureBank/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import User
from django.db.models import CASCADE, SET_NULL
from pyotp import random_base32, TOTP, totp
from .utils import SecureBankException
# from crypto.publickey import RSA
from django.contrib.auth.models import AbstractUser
from django.db import transaction
from passlib.hash import pbkdf2_sha256
from django.core.validators import validate_email
from django.utils import timezone
import datetime





class BankUser(models.Model):
    MAX_REGULAR_EMPLOYEE = 100000
    MAX_AUTO_AUTH = 10000
    BITS = 1024
    # class Meta:
    #     permissions = (
    #         ("is_External_User", "Customer of bank"),
    #         ("is_Internal_User", "Employee has permissions to access User data"),
    #         ("is_Manager", "Manager has permission to access transactions")
    #     )

    TYPES = (
        ('R', 'Regular Employee'),
        ('S', 'System Manager'),
        ('A', 'Admin'),
        ('I', "Individual Customer"),
        ('O', 'Organization'),
    )
    # UID ( Primary Key ), Last Login, Last transaction, last password change, failed login attempt, type of user
    user = models.OneToOneField(User, unique=True, on_delete=CASCADE, primary_key=True)
    phone = models.CharField(max_length=10)
    # EmailID = models.EmailField(max_length=70, null=False)
    address = models.CharField(max_length=250)
    otp_value = models.CharField(max_length=16, default='0', editable=False)
    type_of_user = models.CharField(max_length=1, choices=TYPES)
    publicKey = models.CharField(max_length=10000, default='0', editable=True)
    baseForOtp = models.CharField(max_length=10000, default='base32secret3232', editable=False)


    # private_key = models.CharField()
    # public_key = models.CharField()
    # ListCharField (Internal User, Account access for Internal user). https://django-mysql.readthedocs.io/en/latest/model_fields/list_fields.html

    # TODO: Need to add OTP creation time (for validity of OTP)

    def __str__(self):
        return self.user.username + " " + self.type_of_user

    # def generateCerti(self):
    #     newKey = RSA.generate(BITS)
    #     self.public_key = newKey.publickey().exportKey("PEM")
    #     self.private_key = newKey.exportKey("PEM")
        # sendMail(self.public_key)

    # https://pyotp.readthedocs.io/en/latest/
    def generateOTP(self):

        self.baseForOtp = random_base32()
        print(self.baseForOtp)
        print("base", type(self.baseForOtp))
        otp = TOTP(self.baseForOtp, interval=120).now()
        self.otp_value = otp
        self.save()
        subject = 'OTP From Secure Bank'
        message = self.otp_value
        from_email = 'systemadmin007@gmail.com'
        print(self.user.email)
        to = [self.user.email]
        print(self.otp_value)
        send_mail(subject, message, from_email, to, fail_silently=False)
        return self.otp_value
        # djexmo.send_message(frm='+919717384229', to='+918700543963', te
        # xt='My sms')
        # zerosms.sms(phno=username, passwd=password, receivernum=sendto, message=msg)

    def verifyOTP(self, otp, transaction_key):
        # emsg=pbkdf2_sha256.encrypt(self.publicKey, rounds=12000, salt_size=32)

        baseForOtp = self.baseForOtp
        print(baseForOtp)
        print("base", type(baseForOtp))
        print(self.otp_value)
        print(otp)
        pot = TOTP(baseForOtp, interval=120)
        value = pot.verify(otp)
        print('value', value)

        if not value:
            return value

        try:
            key = self.user.keylist_set.all().filter(key = transaction_key)
        except Exception as e:
            print(e)
            return False

        if len(key) != 0:
            return False


        key = keyList(key = transaction_key, user = self.user)
        print(key)
        key.save()

        print(self.publicKey)
        try:

            flag=pbkdf2_sha256.verify(self.publicKey, transaction_key)
            print(flag)
            print(self.publicKey)
        except:
            print("Exception in key")
            return False
        return pot.verify(otp) and flag

    def EditEmail(self, newEmail):
        self.user.email = newEmail
        self.user.save()



class keyList(models.Model):
    key = models.CharField(primary_key=True, unique = True, max_length=10000, default ='')
    user = models.ForeignKey(User, on_delete=CASCADE)

    def __str__(self):
        return str(self.key)


# class Payment(models.Model):
#     # TODO: Need to create Payment SQLite Table here
#     organization = models.ForeignKey(BankUser, related_name="merchant", null=True)
#     user = models.ForeignKey(Account, related_name='user', null=True)
#     transaction = models.ForeignKey(Transaction, related_name='transaction')
#

class Account(models.Model):
    AccountNumber = models.IntegerField(primary_key=True, unique=True)
    AccountHolder = models.ForeignKey(BankUser, null=True, on_delete=True)
    Balance = models.IntegerField(default=0, editable=True)

    def __str__(self):
        return str(self.AccountNumber)
        # return self.AccountHolder.user.username + " " + str(self.AccountNumber) + " " + str(self.Balance)

    def Credit(self, amount):
        try:
            self.Balance = self.Balance + int(amount)
            self.save()
        except:
            raise SecureBankException('Invalid Amount')

    def Debit(self, amount):
        try:
            if (amount <= 0):
                raise SecureBankException("Invalid Amount")
            if self.Balance < amount:
                raise SecureBankException("Insufficient Funds")
            self.Balance = self.Balance - int(amount)
            self.save()
        except:
            raise SecureBankException('Not Debited!')


class Transaction(models.Model):
    STATUS = (
        ('O', 'OTP required'),
        ('A', 'Approval required'),
        ('P', 'Processed'),
        ('R', 'Rejected'),
        ('E', 'Unsuccessful'),
    )

    TYPE = (
        ('C', 'Credit'),
        ('D', 'Debit'),
        ('T', 'Transfer'),
    )
    Employee = models.ForeignKey(BankUser, null=True, blank=False, on_delete=SET_NULL)
    FromAccount = models.ForeignKey(Account, null=True, related_name='FromAccount', on_delete=SET_NULL, blank=False)
    ToAccount = models.ForeignKey(Account, null=True, related_name='ToAccount', on_delete=SET_NULL, blank=False)
    Amount = models.IntegerField(default=0, editable=True)
    Status = models.CharField(max_length=1, choices=STATUS, editable=True)
    Type = models.CharField(max_length=1, default='T',choices=TYPE,editable=True)
    CreationTime = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        if self.Type == 'T':
            return str(self.id) + " " + str(self.FromAccount.AccountNumber) + " " + str(
                self.ToAccount.AccountNumber) + " " + str(self.Amount)
        elif self.Type == 'D':
            return str(self.id) + " " + str(self.FromAccount.AccountNumber) + " " + str(self.Amount)
        else:
            return str(self.id) + " " + str(self.ToAccount.AccountNumber) + " " + str(self.Amount)

    @staticmethod
    def Create(user, fromAccountNumber, toAccountNumber, amount):
        print("create")
        try:
            amount = int(amount.strip())
            fromAccountNumber = int(fromAccountNumber.strip())
            toAccountNumber = int(toAccountNumber.strip())
        except:
            raise SecureBankException('Error in format of account number/amount')
        if (amount <= 0):
            raise SecureBankException('Negative Ammount')
        fromAccount = Account.objects.filter(AccountNumber=fromAccountNumber)
        if len(fromAccount) == 0:
            raise SecureBankException("Account belongs to someone else")
        fromAccount = fromAccount[0]
        if fromAccount.AccountHolder.user.username != user.username:
            raise SecureBankException("Trying to access someones else account")
        if fromAccount.Balance < amount:
            raise SecureBankException("Insufficient Funds")
        toAccount = Account.objects.filter(AccountNumber=toAccountNumber)
        if len(toAccount) == 0:
            raise SecureBankException('Cannot send to this account')
        toAccount = toAccount[0]
        if fromAccount.AccountNumber == toAccount.AccountNumber:
            raise SecureBankException("Cannot transfer to same account")
        transaction = Transaction(FromAccount=fromAccount, ToAccount=toAccount, Amount=amount, Status='O', Type='T')
        print("Done")
        transaction.save()
        return transaction

    @staticmethod
    def CreateCredit(user, fromAccountNumber, amount):
        print("Do Credit Here")
        try:
            amount = int(amount.strip())
            fromAccountNumber = int(fromAccountNumber.strip())
        except:
            raise SecureBankException('Error in format of account number/amount')
        if (amount <= 0):
            raise SecureBankException('Negative Ammount')
        fromAccount = Account.objects.filter(AccountNumber=fromAccountNumber)
        if len(fromAccount) == 0:
            raise SecureBankException("Account belongs to someone else")
        fromAccount = fromAccount[0]
        if fromAccount.AccountHolder.user.username != user.username:
            raise SecureBankException("Trying to access someones else account")
        transaction = Transaction(FromAccount=None, ToAccount=fromAccount, Amount=amount, Status='A', Type='C')
        print("Done")
        transaction.save()
        return transaction

    @staticmethod
    def CreateDebit(user, fromAccountNumber, amount):
        print("Do Debit Here")
        try:
            amount = int(amount.strip())
            fromAccountNumber = int(fromAccountNumber.strip())
        except:

SecureBankingSystem/SecureBank/templates/SecureBank/authorize_transaction.html
{% extends 'SecureBank/manager_base.html' %}


{% block main_content %}
    <div class="page-content">
        <form action="#" method="post" id="transaction_approve_form" class="fundtransfer-form">
           {% csrf_token %}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                <input type="text" value="" class="mdl-textfield__input" id="transaction" readonly>
                <input type="hidden" value="" name="transaction">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label class="mdl-textfield__label" for="transaction">Transations To approve</label>
                <ul for="transaction" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for transaction in transactions %}
                        <li class="mdl-menu__item" data-val="{{ transaction.id }}">Transaction: {{ transaction.id }} From:{{ transaction.FromAccount.AccountNumber }} To: {{ transaction.ToAccount.AccountNumber }} Amount: {{ transaction.Amount }}</li>
                    <!--<li class="mdl-menu__item" data-val="Account 1" data-selected="true">Account 1</li>-->
                    <!--<li class="mdl-menu__item" data-val="Account 2">Account 2</li>-->
                    <!--<li class="mdl-menu__item" data-val="Account 3">Account 3</li>-->
                    {% endfor %}
                </ul>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                <input type="text" value="" class="mdl-textfield__input" id="transaction__approve_options" readonly>
                <input type="hidden" value="" name="transaction__approve_options">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label class="mdl-textfield__label" for="transaction__approve_options">Options</label>
                <ul for="transaction__approve_options" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                   <li class="mdl-menu__item" data-val="Approve" data-selected="true">Approve</li>
                    <li class="mdl-menu__item" data-val="Reject">Reject</li>
                </ul>
            </div>

            <button type="submit" form="transaction_approve_form" value="Submit" class="mdl-button mdl-button--colored mdl-button--raised mdl-js-button mdl-js-ripple-effect">
            Submit
            </button>
        </form>
    </div>
{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/confirm_transaction.html
{% extends 'SecureBank/userpage_base.html' %}


{% block main_content %}
 <div class="page-content">
        <form action="#" method="post" id="transaction_auth" class="transaction-auth-form">
            {% csrf_token %}

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="password" pattern="^[0-9]{6}" name="transaction_otp" id="transaction_otp">
                <label class="mdl-textfield__label" for="transaction_otp">OTP</label>
                <span class="mdl-textfield__error">Enter 6 digit number</span>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="password"  name="transaction_key" id="transaction_key">
                <label class="mdl-textfield__label" for="transaction_key">Key</label>
                <span class="mdl-textfield__error">Enter Key</span>
            </div>


            <button type="submit" form="transaction_auth" value="Submit" class="mdl-button mdl-button--colored mdl-button--raised mdl-js-button mdl-js-ripple-effect">
            Submit
            </button>
        </form>
    </div>

{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
        <link rel="stylesheet" href="{% static 'SecureBank/style.css' %}" type="text/css">
        <title>Dashboard</title>
{% endblock %}

{% block body %}
    <h3>Hello {{ Username }}</h3>
{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/edit_profile.html
{% extends 'SecureBank/userpage_base.html' %}


{% block main_content %}
    <div class="page-content">
        <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
            <div class="mdl-tabs__tab-bar">
                <a href="#edit_info" class="mdl-tabs__tab is-active">Main Info</a>
            </div>

            <div class="mdl-tabs__panel is-active" id="edit_info">
                <form action="#" method="post" id="edit_info_form" class="profile-form"> 
                   {% csrf_token %}
                    <!-- <div class="profile-name"> -->
                        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                            <input class="mdl-textfield__input" type="text" id="edit_info_firstname" pattern="(?=.{20,})[a-zA-z]+" placeholder="{{firstName}}" readonly>
                            <label class="mdl-textfield__label" for="edit_info_firstname">Name</label>
                            <span class="mdl-textfield__error">Required</span>

                        </div>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <input class="mdl-textfield__input" type="email" name="old_email_address" pattern="^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"  id="old_email_address">
                        <label class="mdl-textfield__label" for="old_email_address">Old Email</label>
                        <span class="mdl-textfield__error">Enter valid Email</span>
                    </div>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <input class="mdl-textfield__input" type="email" name="edit_email_address" pattern="^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"  id="edit_email_address">
                        <label class="mdl-textfield__label" for="edit_email_address">New Email</label>
                        <span class="mdl-textfield__error">Enter valid Email</span>
                    </div>

                    <button type="submit" form="edit_info_form" value="Submit" class="mdl-button mdl-button--colored mdl-button--raised mdl-js-button mdl-js-ripple-effect">
                    Submit
                    </button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/fund_credit.html
{% extends 'SecureBank/userpage_base.html' %}


{% block main_content %}
    <div class="page-content">
        <form action="#" method="post" id="funds_transfer_form" class="fundtransfer-form">  
           {% csrf_token %}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                <input type="text" value="" class="mdl-textfield__input" id="funds_credit_user_account" readonly>
                <input type="hidden" value="" name="funds_credit_user_account">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label class="mdl-textfield__label" for="funds_credit_user_account">Account</label>
                <ul for="funds_transfer_user_account" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for account in accounts %}
                        <li class="mdl-menu__item" data-val="{{ account.AccountNumber }}">{{ account.AccountNumber }}</li>
                    <!--<li class="mdl-menu__item" data-val="Account 1" data-selected="true">Account 1</li>-->
                    <!--<li class="mdl-menu__item" data-val="Account 2">Account 2</li>-->
                    <!--<li class="mdl-menu__item" data-val="Account 3">Account 3</li>-->
                    {% endfor %}
                </ul>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="number" name="funds_credit_amount" pattern="^[1-9][0-9]*$" id="funds_credit_amount">
                <label class="mdl-textfield__label" for="funds_credit_amount">Amount (INR)</label>
                <span class="mdl-textfield__error">Enter integer number greater than 0</span>
            </div>
            <button type="submit" form="funds_transfer_form" value="Submit" class="mdl-button mdl-button--colored mdl-button--raised mdl-js-button mdl-js-ripple-effect">
            Next
            </button>
        </form>
    </div>
{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/fund_debit.html
{% extends 'SecureBank/userpage_base.html' %}


{% block main_content %}
    <div class="page-content">
        <form action="#" method="post" id="funds_transfer_form" class="fundtransfer-form">  
           {% csrf_token %}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                <input type="text" value="" class="mdl-textfield__input" id="funds_debit_user_account" readonly>
                <input type="hidden" value="" name="funds_debit_user_account">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label class="mdl-textfield__label" for="funds_debit_user_account">Account</label>
                <ul for="funds_transfer_user_account" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for account in accounts %}
                        <li class="mdl-menu__item" data-val="{{ account.AccountNumber }}">{{ account.AccountNumber }}</li>
                    <!--<li class="mdl-menu__item" data-val="Account 1" data-selected="true">Account 1</li>-->
                    <!--<li class="mdl-menu__item" data-val="Account 2">Account 2</li>-->
                    <!--<li class="mdl-menu__item" data-val="Account 3">Account 3</li>-->
                    {% endfor %}
                </ul>
            </div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="number" name="funds_debit_amount" pattern="^[1-9][0-9]*$" id="funds_debit_amount">
                <label class="mdl-textfield__label" for="funds_debit_amount">Amount (INR)</label>
                <span class="mdl-textfield__error">Enter integer number greater than 0</span>
            </div>
            <button type="submit" form="funds_transfer_form" value="Submit" class="mdl-button mdl-button--colored mdl-button--raised mdl-js-button mdl-js-ripple-effect">
            Next
            </button>
        </form>
    </div>
{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/funds_transfer.html
{% extends 'SecureBank/userpage_base.html' %}


{% block main_content %}
    <div class="page-content">
        <form action="#" method="post" id="funds_transfer_form" class="fundtransfer-form">  
           {% csrf_token %}
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
                <input type="text" value="" class="mdl-textfield__input" id="funds_transfer_user_account" readonly>
                <input type="hidden" value="" name="funds_transfer_user_account">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
                <label class="mdl-textfield__label" for="funds_transfer_user_account">Account</label>
                <ul for="funds_transfer_user_account" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                    {% for account in accounts %}
                        <li> class="mdl-menu__item" data-val="{{ account.accountNumber }}">{{ account.accountNumber }}</li>
                    <!--<li class="mdl-menu__item" data-val="Account 1" data-selected="true">Account 1</li>-->
                    <!--<li class="mdl-menu__item" data-val="Account 2">Account 2</li>-->
                    <!--<li class="mdl-menu__item" data-val="Account 3">Account 3</li>-->
                    {% endfor %}
                </ul>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" pattern="^[0-9]*$" id="funds_transfer_beneficiary_account">
                <label class="mdl-textfield__label" for="funds_transfer_beneficiary_account">Beneficiary Account Number</label>
                <span class="mdl-textfield__error">Enter a number</span>
            </div>

            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="number" pattern="^[1-9][0-9]*$" id="funds_transfer_amount">
                <label class="mdl-textfield__label" for="funds_transfer_amount">Amount (INR)</label>
                <span class="mdl-textfield__error">Enter integer number greater than 0</span>
            </div>
            <button type="submit" form="funds_transfer_form" value="Submit" class="mdl-button mdl-button--colored mdl-button--raised mdl-js-button mdl-js-ripple-effect">
            Next
            </button>
        </form>
    </div>
{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/home_external.html
{% extends 'home_external_base.html' %}
{% load static %}

{% block head %}
        <link rel="stylesheet" href="{% static 'SecureBank/style.css' %}" type="text/css">
        <title>Home</title>
{% endblock %}

{% block body %}
    <section class="container-fluid" style="margin-top: 80px">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-12 text-right">
                    <h5>{{user}}, Welcome to IIITD Bank - External User</h5>
                </div>
            </div>
        </div>
    </section>

 <nav class="navbar navbar-default">
  <div class="container-fluid" style="...">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Modify Details</a></li>
      <li><a href="#">Make Transaction</a></li>
      <li><a href="#">View Transactions</a></li>
    </ul>
  </div>
</nav>
{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/passbook.html
{% extends 'SecureBank/userpage_base.html' %}


{% block main_content %}
    <div class="page-content mdl-grid">

    	<div class = "summary-balance mdl-cell mdl-grid">
    		<table class="summary-accounts mdl-data-table mdl-js-data-table mdl-shadow--2dp">
				<thead>
					<tr>
                        <th>Creation Date</th>
						<th>Transaction Number</th>
						<th>Amount</th>
						<th>Type</th>
						<th>From Account</th>
                        <th>To Account</th>
                        <th>Status</th>
					</tr>
				</thead>
				<tbody clas="summary-accounts-body">
				{% for transaction in transactions %}
                <tr><td>{{transaction.CreationTime}}</td><td>{{ transaction.id }}</td><td>{{ transaction.Amount }}</td><td>{{ transaction.get_Type_display }}</td><td>{{ transaction.FromAccount.AccountNumber }}</td><td>{{ transaction.ToAccount.AccountNumber }}</td><td>{% if transaction.Status == 'O' %} OTP Required {% endif %}{% if transaction.Status == 'A' %} Approval required {% endif %}{% if transaction.Status == 'P' %} Processed {% endif %}{% if transaction.Status == 'R' %} Rejected {% endif %}{% if transaction.Status == 'E' %} Unsuccessful {% endif %}
</td></tr>
				{% endfor %}
				</tbody>
			</table>
    	</div>

{% if trasaction.Status == 'O' %} OTP Required {% endif %}{% if trasaction.Status == 'A' %} Approval required {% endif %}{% if trasaction.Status == 'P' %} Processed {% endif %}{% if trasaction.Status == 'R' %} Rejected {% endif %}{% if trasaction.Status == 'E' %} Unsuccessful {% endif %}
    	
    </div>
{% endblock %}

SecureBankingSystem/SecureBank/templates/SecureBank/summary.html
{% extends 'SecureBank/userpage_base.html' %}


{% block main_content %}


    <div class="page-content mdl-grid ">
		<div class = "summary-balance mdl-card__title mdl-shadow--2dp mdl-card--border mdl-cell mdl-cell--3-col mdl-grid">
				<span class="mdl-card__title-text">Total Balance: &nbsp;</span>
				<span class="mdl-card__title-text mdl-color-text--blue"> Rs.{{ totalBalance }}</span>
			</div>
				<!-- <div class = "summary-balance mdl-cell mdl-cell--2-col mdl-grid">
						<span>Last Activity: </span>
				</div>
				<div class = "summary-balance mdl-cell mdl-cell--2-col mdl-grid">
					<span>Last password change: </span>
				</div> -->
	
			<div class = "summary-balance mdl-card__title mdl-shadow--2dp mdl-card--border mdl-cell  mdl-cell--5-col mdl-grid">
				<span class="mdl-card__title-text">Last Login: &nbsp;</span>
				<span class="mdl-card__title-text mdl-color-text--blue">{{ lastLogin }}</span>
			</div>
			<!-- <div class = "summary-balance mdl-cell mdl-cell--2-col mdl-grid">
				<span>Last Failed Login Attempt: </span>
			</div> -->
		<div class = "summary-balance  mdl-cell--4-col mdl-cell mdl-grid">
			<table class="summary-accounts mdl-cell--4-col mdl-data-table mdl-js-data-table mdl-shadow--2dp">
				<thead>
					<tr>
						<th>Account Number</th>
						<th>Balance</th>
					</tr>
				</thead>
				<tbody clas="summary-accounts-body">
				{% for account in accounts %}
					<tr><td>{{ account.AccountNumber }}</td><td>{{ account.Balance }}</td></tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
    </div>
{% endblock %}